table d_event_type
	lineageTag: a6c82714-eff8-4b6c-89ea-dbfcfcb43301

	column event_type
		dataType: string
		lineageTag: b2b211ac-4015-40af-9fd6-460a5d79d5f6
		summarizeBy: none
		sourceColumn: event_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Evento
		dataType: string
		lineageTag: 11519534-167c-4c50-afed-51cc2e146324
		summarizeBy: none
		sourceColumn: Evento

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition d_event_type = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Fonte = PowerPlatform.Dataflows(null),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"5381a7f5-5b4c-4fa7-96d6-48992d85d88e" = Workspaces{[workspaceId="5381a7f5-5b4c-4fa7-96d6-48992d85d88e"]}[Data],
				    #"32502a54-a25e-49da-96b6-b9d541c6dc0b" = #"5381a7f5-5b4c-4fa7-96d6-48992d85d88e"{[dataflowId="32502a54-a25e-49da-96b6-b9d541c6dc0b"]}[Data],
				    event_type_ = #"32502a54-a25e-49da-96b6-b9d541c6dc0b"{[entity="event_type",version=""]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(event_type_, each ([event_type] = "ACQUISITION" or [event_type] = "REPURCHASE"))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

